//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 16/12/2013 10:05:54 AM
namespace DemoKendo
{
    
    /// <summary>
    /// There are no comments for testEntities in the schema.
    /// </summary>
    public partial class testEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new testEntities object using the connection string found in the 'testEntities' section of the application configuration file.
        /// </summary>
        public testEntities() : 
                base("name=testEntities", "testEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new testEntities object.
        /// </summary>
        public testEntities(string connectionString) : 
                base(connectionString, "testEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new testEntities object.
        /// </summary>
        public testEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "testEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Brand in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Brand> Brand
        {
            get
            {
                if ((this._Brand == null))
                {
                    this._Brand = base.CreateQuery<Brand>("[Brand]");
                }
                return this._Brand;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Brand> _Brand;
        /// <summary>
        /// There are no comments for Merchandise in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Merchandise> Merchandise
        {
            get
            {
                if ((this._Merchandise == null))
                {
                    this._Merchandise = base.CreateQuery<Merchandise>("[Merchandise]");
                }
                return this._Merchandise;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Merchandise> _Merchandise;
        /// <summary>
        /// There are no comments for Brand in the schema.
        /// </summary>
        public void AddToBrand(Brand brand)
        {
            base.AddObject("Brand", brand);
        }
        /// <summary>
        /// There are no comments for Merchandise in the schema.
        /// </summary>
        public void AddToMerchandise(Merchandise merchandise)
        {
            base.AddObject("Merchandise", merchandise);
        }
    }
    /// <summary>
    /// There are no comments for testModel.Brand in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="testModel", Name="Brand")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Brand : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Brand object.
        /// </summary>
        /// <param name="id">Initial value of id.</param>
        /// <param name="name">Initial value of name.</param>
        /// <param name="type">Initial value of type.</param>
        public static Brand CreateBrand(int id, string name, string type)
        {
            Brand brand = new Brand();
            brand.id = id;
            brand.name = name;
            brand.type = type;
            return brand;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this.ReportPropertyChanging("name");
                this._name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("name");
                this.OnnameChanged();
            }
        }
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// There are no comments for Property type in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string type
        {
            get
            {
                return this._type;
            }
            set
            {
                this.OntypeChanging(value);
                this.ReportPropertyChanging("type");
                this._type = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("type");
                this.OntypeChanged();
            }
        }
        private string _type;
        partial void OntypeChanging(string value);
        partial void OntypeChanged();
    }
    /// <summary>
    /// There are no comments for testModel.Merchandise in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// name
    /// description
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="testModel", Name="Merchandise")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Merchandise : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Merchandise object.
        /// </summary>
        /// <param name="id">Initial value of id.</param>
        /// <param name="name">Initial value of name.</param>
        /// <param name="description">Initial value of description.</param>
        public static Merchandise CreateMerchandise(int id, string name, string description)
        {
            Merchandise merchandise = new Merchandise();
            merchandise.id = id;
            merchandise.name = name;
            merchandise.description = description;
            return merchandise;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this.ReportPropertyChanging("name");
                this._name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("name");
                this.OnnameChanged();
            }
        }
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// There are no comments for Property description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this._description;
            }
            set
            {
                this.OndescriptionChanging(value);
                this.ReportPropertyChanging("description");
                this._description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("description");
                this.OndescriptionChanged();
            }
        }
        private string _description;
        partial void OndescriptionChanging(string value);
        partial void OndescriptionChanged();
    }
}
